# Matrix Decomposition

In [22]:
import numpy as np

## Eigen Decomposition

In [23]:
A = np.array([[2, 2],
              [-1, 1]])

In [24]:
e, v = np.linalg.eig(A*A)

print("Eigen values = ")
print(e)

print("Eigen vectors = ")
print(v)

Eigen values = 
[5. 0.]
Eigen vectors = 
[[ 0.9701425  -0.70710678]
 [ 0.24253563  0.70710678]]


## SVD Decomposition

$$
\mathbf{A}=\mathbf{U} \mathbf{\Sigma} \mathbf{V}^T
$$

where:

* $\mathbf{U}$ is an orthogonal matrix
* $\mathbf{\Sigma}$ is an rectangular diagonal matrix
* $\mathbf{V}$ is an orthogonal matrix


The SVD of $\mathbf{A}$ is closely related to the eigendecompositions of $\mathbf{A} \mathbf{A}^T$ and $\mathbf{A}^T \mathbf{A}$
- The left singular vectors are the eigenvectors of $\mathbf{A A}^T$
- The right singular vectors are the eigenvectors of $\mathbf{A}^T \mathbf{A}$
- The singular values are the square roots of the eigenvalues of both $\mathbf{A A}^T$ and $\mathbf{A}^T \mathbf{A}$


In [25]:
A = np.array([[2, 2],
              [-1, 1]])

In [26]:
U, S, VT = np.linalg.svd(A)
print("U = ")
print(U)

print("S = ")
print(S)

print("VT = ")
print(VT)

U = 
[[-1.00000000e+00  1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
S = 
[2.82842712 1.41421356]
VT = 
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


## SVD Decomposition of an Square Symmetric and Positive Definite Matrix

A square matrix is called positive definite if it is symmetric and all its eigenvalues $\lambda$ are positive, that is $\lambda > 0$.

Additionally, if $\mathbf{A}$ is positive definite, then it is invertible and $\det(\mathbf{A}) > 0$.

For square symmetric and positive definite matrix:

$$\text{eig}(\mathbf{A})  = \mathbf{\Sigma} $$

In [27]:
A = np.array([[2, 1],
              [1, 1]])

U, S, VT = np.linalg.svd(A)
e, v = np.linalg.eig(A)



In [30]:
print(S)
print(e)

[2.61803399 0.38196601]
[2.61803399 0.38196601]
